### PR TITLE
Upgrade to CircleCI 2.1.

### PR DESCRIPTION
**Pull request by felicianotech**
Getting the tests to pass on my fork was a b****. Oo

Anyway, converted the config over to 2.1 and then used parameterized jobs to reduce the lines of config needed. Went from 261 lines to 137.

### CODE REVIEW

**Comment by levlaz** [comment]
Thank you so much @felicianotech, I meant to do this eventually :) 

> Getting the tests to pass on my fork was a b****. Oo

Yeah this is a tough one since I am running some "integration tests" against a real thing that requires API usage. Not sure of a good approach here. 

I don't really want to allow secrets in forks. Maybe integration tests should be disabled for forks or something?

**Comment by levlaz** [comment]
Im getting failures on the integration tests now :'(

**Comment by felicianotech** [comment]
:frowning_face: 

For one of the build's errors:

```
Build-agent version 0.1.1062-dce5e86e (2018-11-10T01:11:11+0000)
Configuration errors: 2 errors occurred:

* Configuration version 2.1 requires the "Enable Build Processing" project setting. Enable Build Processing under Project Settings -> Advanced Settings. In order to retrigger build processing, you must push a new commit.
* Cannot find a job named `integration` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
```

My guess here is that for your integration tests, you're using an original API endpoint when with 2.1, you'd need to use the new Workflows compliant endpoint?

**Comment by levlaz** [comment]
@felicianotech thanks that makes sense. I think the broader issue is that this wrapper does not really work with 2.1 or workflows at all right now. 

I am going to add a warning about this to the docs and start working on proper support.

**Pull request merged**
